import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/features/top-nav";
import Breadcrumbs from "@/components/features/breadcrumbs";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSideBar } from "@/components/features/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import { scanRoutes } from "@/lib/scan-routes";
import { RoutesProvider } from "@/components/context/route-context";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const routes = scanRoutes("app");
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <RoutesProvider routes={routes}>
              <SidebarProvider defaultOpen={false}>
                <AppSideBar />
                <SidebarInset>
                  <main>
                    <TopNav trigger={<SidebarTrigger />} />
                    {/* <div className="min-h-4 w-full mt-4 px-8">
                      <Breadcrumbs />
                    </div> */}
                    {children}
                  </main>
                </SidebarInset>
              </SidebarProvider>
            </RoutesProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
